### ISSUE TITLE
Multiple Gnome3 checks fails even if Gnome isn't installed.

### ISSUE THREAD

**Issue by konstruktoid** [ComplianceAsCode/content#2445]
#### Description of problem:

Multiple Gnome3 checks fails even if Gnome isn't installed.

E.g. CCE-80108-4, CCE-80110-0, CCE-80370-0

Red Hat Enterprise Linux 7 Security Technical Implementation Guide V1 R2:
`Note: If the system does not have GNOME installed, this requirement is Not Applicable.`

```
$ rpm -qa | grep -E 'gnome|gdm' | wc -l
0
```

#### SCAP Security Guide Version:

Using master branch and building with Docker.

```
$ oscap info /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml | grep -E -i 'Ref-Id|generated'
 Generated: (null)
  Ref-Id: scap_org.open-scap_cref_ssg-rhel7-xccdf-1.2.xml
    Generated: 2017-11-01
  Ref-Id: scap_org.open-scap_cref_ssg-rhel7-pcidss-xccdf-1.2.xml
    Generated: 2017-11-01
  Ref-Id: scap_org.open-scap_cref_ssg-rhel7-oval.xml
  Ref-Id: scap_org.open-scap_cref_ssg-rhel7-ocil.xml
  Ref-Id: scap_org.open-scap_cref_ssg-rhel7-cpe-oval.xml
  Ref-Id: scap_org.open-scap_cref_ssg-rhel7-oval.xml000
  Ref-Id: scap_org.open-scap_cref_ssg-rhel7-ocil.xml000
  Ref-Id: scap_org.open-scap_cref_ssg-rhel7-cpe-dictionary.xml
```

#### Operating System Version:

```
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.4 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"
```

#### Expected Results:

Gnome checks should be marked `notapplicable` and not `failed`.

**Comment by redhatrises** [comment]
@konstruktoid as this is OVAL returning pass/fail, so the OVAL checks will have to return pass if `gdm` is not installed.

**Comment by redhatrises** [comment]
@konstruktoid will you confirm that the `dconf` package is not installed?

**Comment by konstruktoid** [comment]
The `dconf` package is installed, due to `emacs` dependencies. 

```
$ rpm -qa | grep -E 'dconf|gdm|gnome|emacs'
emacs-filesystem-24.3-20.el7_4.noarch
emacs-24.3-20.el7_4.x86_64
emacs-common-24.3-20.el7_4.x86_64
dconf-0.26.0-2.el7.x86_64
$
```

**Comment by redhatrises** [comment]
There is lies the problem. Just as the old gconf checks for `gconftool-2` whether or not gdm is installed, so do the same dconf checks check if `dconf` is installed because you can now configure this items.

**Comment by konstruktoid** [comment]
And it seemed getting rid of `emacs` wasn't an option ...
The checks seems to miss the configuration though.

```$ cat /etc/dconf/db/local.d/00-security-settings
[org/gnome/desktop/session]
idle-delay=uint32 900

[org/gnome/desktop/screensaver]
lock-delay=uint32 5
idle_activation_enabled=true
lock-enabled=true

[org/gnome/login-screen]
banner-message-enable=true
```

`shared/checks/oval/dconf_gnome_screensaver_idle_delay.xml:    <ind:pattern operation="pattern match">^\[org/gnome/desktop/session]([^\n]*\n+)+?idle-delay=uint32[\s][0-9]*$</ind:pattern>`
```$ sudo grep -R -P '^\[org/gnome/desktop/session]([^\n]*\n+)+?idle-delay=uint32[\s][0-9]*$' /etc/dconf/*
$ sudo grep -R -P '^idle-delay=uint32[\s][0-9]*$' /etc/dconf/*
/etc/dconf/db/local.d/00-security-settings:idle-delay=uint32 900
$
```

`shared/checks/oval/dconf_gnome_screensaver_lock_enabled.xml:    <ind:pattern operation="pattern match">^\[org/gnome/desktop/screensaver]([^\n]*\n+)+?lock-enabled=true$</ind:pattern>`
```$ sudo grep -R -P '^\[org/gnome/desktop/screensaver]([^\n]*\n+)+?lock-enabled=true$' /etc/dconf/*
$ sudo grep -R -P '^lock-enabled=true$' /etc/dconf/*
/etc/dconf/db/local.d/00-security-settings:lock-enabled=true
$```

`shared/checks/oval/dconf_gnome_screensaver_lock_delay.xml:    <ind:pattern operation="pattern match">^\[org/gnome/desktop/screensaver]([^\n]*\n+)+?lock-delay=uint32[\s][0-9]*$</ind:pattern>`
```$ sudo grep -R -P '^\[org/gnome/desktop/screensaver]([^\n]*\n+)+?lock-delay=uint32[\s][0-9]*$' /etc/dconf/*
$ sudo grep -R -P 'lock-delay=uint32[\s][0-9]*$' /etc/dconf/*
/etc/dconf/db/local.d/00-security-settings:lock-delay=uint32 5
$```

**Comment by OnceUponALoop** [comment]
Can we resolve this by checking `package_gdm_installed`? 

Would that be enough to indicate a gnome installation or would we also need to create a new test for `package_gnome-desktop3_installed`?

I just checked and you can indeed install gdm without gnome (for xinetd auth maybe?) so probably something along the lines of
- Identify the tests related to gdm and add the `package_gdm_installed` test to them
- Identify the tests related to gnome and add newly created `package_gnome-desktop3_installed` test to them

What do you think?

**Comment by OnceUponALoop** [comment]
I discussed this issue with @redhatrises on IRC, it would seem that we're going to have to add these conf changes even if we don't have gnome installed. 

The logic being that gnome can always be installed down the line and SSG is getting push-back about using package checks in the oval checks (all of these require a package_dconf_installed check btw 😕 )

One thing to note is that some of these settings will not be defined in dconf if you don't have the relevant package installed (ex. gdm).

I ended up just adding them as follows below, one thing i noticed while doing that is the regex could use some love, additional lines or comments end up failing the check. 

``` bash

# Required since gdm path doesn't exist on systems where gdm isn't installed
mkdir -p /etc/dconf/db/gdm.d/locks

# GDM Changes
echo '
[org/gnome/login-screen]
disable-user-list=true
disable-restart-buttons=true
enable-smartcard-authentication=true
allowed-failures=3
banner-message-enable=true
banner-message-text=string '"'"'BANNER TEXT'"'"'
' >> /etc/dconf/db/gdm.d/00-security-settings

# GDM Locks
echo '
/org/gnome/login-screen/disable-user-list
/org/gnome/login-screen/disable-restart-buttons
/org/gnome/login-screen/enable-smartcard-authentication
/org/gnome/login-screen/allowed-failures
/org/gnome/login-screen/banner-message-enable
/org/gnome/login-screen/banner-message-text
' >> /etc/dconf/db/gdm.d/locks/00-security-settings-lock

# GNOME Changes
echo '
[org/gnome/desktop/session]
idle-delay='''uint32 900'''

[org/gnome/desktop/screensaver]
idle-activation-enabled=true
lock-enabled=true
lock-delay=uint32 0
picture-uri=string '"''"'
show-full-name-in-top-bar=false

[org/gnome/settings-daemon/plugins/media-keys]
logout=string '"''"'

[org/gnome/desktop/lockdown]
user-administration-disabled=true

[org/gnome/system/location]
enabled=false

[org/gnome/clocks]
geolocation=false

[org/gnome/nm-applet]
disable-wifi-create=true
suppress-wireless-networks-available=true

[org/gnome/Vino]
authentication-methods=['"'"'vnc'"'"']

[org/gnome/Vino]
require-encryption=true

[org/gnome/desktop/media-handling]
automount=false
automount-open=false
autorun-never=true

[org/gnome/desktop/thumbnailers]
disable-all=true
' >> /etc/dconf/db/local.d/00-security-settings

# GNOME LOCKS
echo '
/org/gnome/desktop/session/idle-delay
/org/gnome/desktop/screensaver/idle-activation-enabled
/org/gnome/desktop/screensaver/lock-enabled
/org/gnome/desktop/screensaver/lock-delay
/org/gnome/desktop/screensaver/picture-uri
/org/gnome/desktop/screensaver/show-full-name-in-top-bar
/org/gnome/settings-daemon/plugins/media-keys/logout
/org/gnome/desktop/lockdown/user-administration-disabled
/org/gnome/system/location/enabled
/org/gnome/clocks/geolocation
/org/gnome/nm-applet/disable-wifi-create
/org/gnome/nm-applet/suppress-wireless-networks-available
/org/gnome/Vino/authentication-methods
/org/gnome/Vino/require-encryption
/org/gnome/desktop/media-handling/automount
/org/gnome/desktop/media-handling/automount-open
/org/gnome/desktop/media-handling/autorun-never
/org/gnome/desktop/thumbnailers/disable-all
' >> /etc/dconf/db/local.d/locks/00-security-settings-lock
```

**Comment by shawndwells** [comment]
On 2/26/18 5:49 PM, Firas AlShafei wrote:
>
> I discussed this issue with @redhatrises
> <https://github.com/redhatrises> on IRC, it would seem that we're
> going to have to add these conf changes even if we don't have gnome
> installed.
>
> The logic being that gnome can always be installed down the line and
> SSG is getting push-back about using package checks in the oval checks
> (all of these require a package_dconf_installed check btw 😕 )
>
> One thing to note is that some of these settings will not be defined
> in dconf if you don't have the relevant package installed (ex. gdm).
>
> I ended up just adding them as follows below, one thing i noticed
> while doing that is the regex could use some love, additional lines or
> comments end up failing the check.
>

Not sure I understand. Other configuration checks ensure the associated
daemon/subsystem is installed. For example, the SSH checks:

https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/checks/oval/sshd_disable_root_login.xml#L13


For things that require GNOME to be installed, having
package_gnome_installed (or whatever it should be) makes sense. Would
have to explore a bit deeper to understand what capabilities are
provided in base GDM vs GNOME vs X11 (example: all would need a screen
saver, so just checking of GNOME installed would likely not be sufficient).

**Comment by OnceUponALoop** [comment]
@shawndwells that's what I assumed initially, especially since most of these checks are already dependent on the `package_dconf_installed` check. 

I already addressed the point you brought up about the capabilities being divided over a few packages. Please review the PR #2616  i submitted, there's a table outlining the dependencies for each with references.

**Comment by redhatrises** [comment]
This was per PR that Maura in relation to using Gconf package check rather than GDM package check in RHEL6. The same logic was applied for RHEL7. 

That said. @OnceUponALoop discovered earlier today that certain dconf configuration DBs don't get installed without certain packages being installed, so the logic does need to change. However, the logic in PR #2616 is still not correct. The package installed OVAL needs to be removed and added to the templates. Also, the OVAL changes in PR are not really correct either. The PR should be updated to match the logic that was done to SSH to return "not applicable" as in #2272.

**Comment by linuxdan** [comment]
What is the status of this, folks ?
Put in the settings whether Gnome is there or not ?

**Comment by OnceUponALoop** [comment]
@linuxdan I tried to fix it but ran out of time and haven't been able to get back into ssg for a while now.
If i remember correctly you're not able to make all the changes as some of the dconf db settings weren't populated if gnome wasn't installed, meaning you wouldn't be able to make all the required settings anyways.

I'm just surprised this isn't encountered more often, I assumed more people would be running without the additional gnome overhead 😐

**Comment by redhatrises** [comment]
Basically this is a low priority. People run scans and do the following:

1. Ignore the fact that gnome checks fail because they know it is not needed in their environment.
2. Ignore the gnome checks because it is documented in their SSP that gnome is not installed.
3. Tailor out the gnome checks using `scap-workbench` which is the recommended way handling environment differences such as not having gnome installed.

**Comment by shawndwells** [comment]
Is the fix something more than adding logic to check if GNOME is installed prior to evaluation?

**Comment by shawndwells** [comment]
Some of the OVAL appear to have this already, e.g. for smartcard:

`````
   <criteria operator="OR">
      <extend_definition comment="dconf installed" definition_ref="package_dconf_installed" negate="true" />
      <criteria comment="Enable smartcard authentication and prevent user from changing it" operator="AND">
        <extend_definition comment="dconf user profile exists" definition_ref="enable_dconf_user_profile" />
        <criterion comment="Enable smartcard authentication" test_ref="test_enable_gnome_smartcard" />
        <criterion comment="Prevent user from changing" test_ref="test_prevent_user_disable_smartcard" />
      </criteria>

`````

**Comment by shawndwells** [comment]
Read the entire thread and old PR (https://github.com/ComplianceAsCode/content/pull/2616). 

Seems reasonable to resurrect https://github.com/ComplianceAsCode/content/pull/2616 to solve this problem (if someone wants to take that on)

**Comment by redhatrises** [comment]
@shawndwells we need to make the checks `not applicable` not `pass/fail` as `pass/fail` is the incorrect returned results and lead to incorrect understanding of scans and scan results.
